### ISSUE TITLE
Allow supplying sources from the command line

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/adnix-rs#1]
While hardcoding a 'default' set of sources works for the job I use adnix for, I'd like for this to be more extensible for others and eventually make it's way to crates.io

Proposal: Allow passing a file with lines of sources delimited by a pipe (`|`) or something similar that won't ever be in a URL.

Sample `sources_file`:
```
Yoyo|http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
Malware Domain List|http://www.malwaredomainlist.com/hostslist/hosts.txt
```

Calling `adnix --sources-file ./sources_file` replaces my hard-coded defaults with items loaded from this list.

**Comment by MichelKansou** [comment]
I'm interested in this can I take it ?
